# Generated by Django 3.0.7 on 2021-10-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'pagina', 'verbose_name_plural': 'paginas'},
        ),
    ]
